/**
 * @typedef {object} API_bootstrapStatic
 * @property {object[]} events
 * @property {number} events.id
 * @property {string} events.name
 * @property {string} events.deadline_time
 * @property {number} events.average_entry_score
 * @property {boolean} events.finished
 * @property {boolean} events.data_checked
 * @property {null} events.highest_scoring_entry
 * @property {number} events.deadline_time_epoch
 * @property {number} events.deadline_time_game_offset
 * @property {null} events.highest_score
 * @property {boolean} events.is_previous
 * @property {boolean} events.is_current
 * @property {boolean} events.is_next
 * @property {boolean} events.cup_leagues_created
 * @property {boolean} events.h2h_ko_matches_created
 * @property {object[]|} events.chip_plays
 * @property {string} events.chip_plays.chip_name
 * @property {number} events.chip_plays.num_played
 * @property {null} events.most_selected
 * @property {null} events.most_transferred_in
 * @property {null} events.top_element
 * @property {null} events.top_element_info
 * @property {number} events.transfers_made
 * @property {null} events.most_captained
 * @property {null} events.most_vice_captained
 * @property {object} game_settings
 * @property {number} game_settings.league_join_private_max
 * @property {number} game_settings.league_join_public_max
 * @property {number} game_settings.league_max_size_public_classic
 * @property {number} game_settings.league_max_size_public_h2h
 * @property {number} game_settings.league_max_size_private_h2h
 * @property {number} game_settings.league_max_ko_rounds_private_h2h
 * @property {string} game_settings.league_prefix_public
 * @property {number} game_settings.league_points_h2h_win
 * @property {number} game_settings.league_points_h2h_lose
 * @property {number} game_settings.league_points_h2h_draw
 * @property {boolean} game_settings.league_ko_first_instead_of_random
 * @property {null} game_settings.cup_start_event_id
 * @property {null} game_settings.cup_stop_event_id
 * @property {null} game_settings.cup_qualifying_method
 * @property {null} game_settings.cup_type
 * @property {number} game_settings.squad_squadplay
 * @property {number} game_settings.squad_squadsize
 * @property {number} game_settings.squad_team_limit
 * @property {number} game_settings.squad_total_spend
 * @property {number} game_settings.ui_currency_multiplier
 * @property {boolean} game_settings.ui_use_special_shirts
 * @property {} game_settings.ui_special_shirt_exclusions
 * @property {number} game_settings.stats_form_days
 * @property {boolean} game_settings.sys_vice_captain_enabled
 * @property {number} game_settings.transfers_cap
 * @property {number} game_settings.transfers_sell_on_fee
 * @property {string[]} game_settings.league_h2h_tiebreak_stats
 * @property {string} game_settings.timezone
 * @property {object[]} phases
 * @property {number} phases.id
 * @property {string} phases.name
 * @property {number} phases.start_event
 * @property {number} phases.stop_event
 * @property {object[]} teams
 * @property {number} teams.code
 * @property {number} teams.draw
 * @property {null} teams.form
 * @property {number} teams.id
 * @property {number} teams.loss
 * @property {string} teams.name
 * @property {number} teams.played
 * @property {number} teams.points
 * @property {number} teams.position
 * @property {string} teams.short_name
 * @property {number} teams.strength
 * @property {null} teams.team_division
 * @property {boolean} teams.unavailable
 * @property {number} teams.win
 * @property {number} teams.strength_overall_home
 * @property {number} teams.strength_overall_away
 * @property {number} teams.strength_attack_home
 * @property {number} teams.strength_attack_away
 * @property {number} teams.strength_defence_home
 * @property {number} teams.strength_defence_away
 * @property {number} teams.pulse_id
 * @property {number} total_players
 * @property {object[]} elements
 * @property {null|number} elements.chance_of_playing_next_round
 * @property {null} elements.chance_of_playing_this_round
 * @property {number} elements.code
 * @property {number} elements.cost_change_event
 * @property {number} elements.cost_change_event_fall
 * @property {number} elements.cost_change_start
 * @property {number} elements.cost_change_start_fall
 * @property {number} elements.dreamteam_count
 * @property {number} elements.element_type
 * @property {string} elements.ep_next
 * @property {null} elements.ep_this
 * @property {number} elements.event_points
 * @property {string} elements.first_name
 * @property {string} elements.form
 * @property {number} elements.id
 * @property {boolean} elements.in_dreamteam
 * @property {string} elements.news
 * @property {null|string} elements.news_added
 * @property {number} elements.now_cost
 * @property {string} elements.photo
 * @property {string} elements.points_per_game
 * @property {string} elements.second_name
 * @property {string} elements.selected_by_percent
 * @property {boolean} elements.special
 * @property {null} elements.squad_number
 * @property {string} elements.status
 * @property {number} elements.team
 * @property {number} elements.team_code
 * @property {number} elements.total_points
 * @property {number} elements.transfers_in
 * @property {number} elements.transfers_in_event
 * @property {number} elements.transfers_out
 * @property {number} elements.transfers_out_event
 * @property {string} elements.value_form
 * @property {string} elements.value_season
 * @property {string} elements.web_name
 * @property {number} elements.minutes
 * @property {number} elements.goals_scored
 * @property {number} elements.assists
 * @property {number} elements.clean_sheets
 * @property {number} elements.goals_conceded
 * @property {number} elements.own_goals
 * @property {number} elements.penalties_saved
 * @property {number} elements.penalties_missed
 * @property {number} elements.yellow_cards
 * @property {number} elements.red_cards
 * @property {number} elements.saves
 * @property {number} elements.bonus
 * @property {number} elements.bps
 * @property {string} elements.influence
 * @property {string} elements.creativity
 * @property {string} elements.threat
 * @property {string} elements.ict_index
 * @property {number} elements.influence_rank
 * @property {number} elements.influence_rank_type
 * @property {number} elements.creativity_rank
 * @property {number} elements.creativity_rank_type
 * @property {number} elements.threat_rank
 * @property {number} elements.threat_rank_type
 * @property {number} elements.ict_index_rank
 * @property {number} elements.ict_index_rank_type
 * @property {number|null} elements.corners_and_indirect_freekicks_order
 * @property {string} elements.corners_and_indirect_freekicks_text
 * @property {number|null} elements.direct_freekicks_order
 * @property {string} elements.direct_freekicks_text
 * @property {null|number} elements.penalties_order
 * @property {string} elements.penalties_text
 * @property {object[]} element_stats
 * @property {string} element_stats.label
 * @property {string} element_stats.name
 * @property {object[]} element_types
 * @property {number} element_types.id
 * @property {string} element_types.plural_name
 * @property {string} element_types.plural_name_short
 * @property {string} element_types.singular_name
 * @property {string} element_types.singular_name_short
 * @property {number} element_types.squad_select
 * @property {number} element_types.squad_min_play
 * @property {number} element_types.squad_max_play
 * @property {boolean} element_types.ui_shirt_specific
 * @property {number[]|} element_types.sub_positions_locked
 * @property {number} element_types.element_count
 */
