import React from 'react';
import { Box, HStack, Text } from 'native-base';

const TeamCardHeaderB = () => {
    return (
        <Box
            bg="gray.800"
            mb={1}
            borderColor={'darkslategray'}
            borderWidth={'1'}
        >
            <HStack w={'100%'} h="2em">
                <Text
                    w={'10%'}
                    alignSelf="center"
                    textAlign={'center'}
                    fontSize="0.8em"
                    fontWeight={100}
                >
                    Rank
                </Text>
                <Text
                    w={'5%'}
                    alignSelf="center"
                    textAlign={'center'}
                    fontSize="0.8em"
                    fontWeight={100}
                ></Text>
                <Text
                    alignSelf="start"
                    justifySelf={'center'}
                    fontSize="0.8em"
                    w={'15%'}
                ></Text>
                <Text
                    alignSelf="center"
                    textAlign={'start'}
                    fontSize="0.8em"
                    fontWeight={100}
                    w={'25%'}
                >
                    Team
                </Text>
                <Text
                    w={'12%'}
                    alignSelf="center"
                    textAlign={'center'}
                    fontSize="0.8em"
                    fontWeight={100}
                >
                    Record
                </Text>
                <Text
                    w={'8.25%'}
                    alignSelf="center"
                    textAlign={'center'}
                    fontSize="0.8em"
                    fontWeight={100}
                >
                    PF
                </Text>
                <Text
                    w={'8.25%'}
                    alignSelf="center"
                    textAlign={'center'}
                    fontSize="0.8em"
                    fontWeight={100}
                >
                    PA
                </Text>
                <Text
                    w={'8.25%'}
                    alignSelf="center"
                    textAlign={'center'}
                    fontSize="0.8em"
                    fontWeight={100}
                >
                    +/-
                </Text>
                <Text
                    w={'8.25%'}
                    alignSelf="center"
                    textAlign={'center'}
                    fontSize="0.8em"
                    fontWeight={100}
                >
                    {'Pts'}
                </Text>
            </HStack>
        </Box>
    );
};

export default TeamCardHeaderB;
